# -*- coding: utf-8 -*-
"""Lưu Hải Phú - 2256210046 - LT&KTDL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gx5pwDcDOVuct-3KEI7MHeOv18mkqCcn

**BƯỚC 1: CLONE TRÊN GITHUB**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt comet_ml  # install

import torch
import utils
display = utils.notebook_init()  # checks

"""**BƯỚC 2: TRAIN DATA**
- ĐỐI VỚI DATASET GITHUB KHÔNG CẦN TRAIN
- ĐỐI VỚI DATASET TỰ TẠO UPLOAD FILE RAR UNRAR RỒI TRAIN


"""

!unrar x /content/coco128.rar

!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache

!python train.py --data /content/yolov5/data/coco128.yaml --cfg yolov5s.yaml --weights yolov5s.pt --batch-size 16 --epochs 50

"""**BƯỚC 3: DETECT DATASET**
- Dòng 1 thuộc dataset coco128 - Github
- Dòng 2 thuộc dataset coco128 - cá nhân
"""

!python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images

!python detect (1).py --weights /content/yolov5/runs/train/exp2/weights/best.pt --conf 0.1 --source 0